config/routes.rb
Openpicsmap::Application.routes.draw do
  
  get "sessions/new"

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions

  resources :pics do
    collection do
      get :map
    end
  end

  root :to => 'pics#index'

end

app/models/pic.rb
require "yaml"

class Pic < ActiveRecord::Base

  attr_accessible :address, :description, :latitude, :longitude, :taken_at, :title, :image
  # geocoded_by :address

  validates :image, :presence => true

  mount_uploader :image, ImageUploader

  # after_validation :geocode, :if => :address_changed?
  before_create :default_title
  before_save :parse_exif, :if => :image_changed?
  before_destroy :destroy_image

  def default_title
    self.title = File.basename(image.filename, '.*').titleize if image and (title.nil? or title.empty?)
  end

  def full_description
    if description.nil? or description.empty?
      self.title
    else
      [self.title, self.description].join(" -- ")
    end
  end

  def as_json(options = { })
    hash = super(options) || {}
    hash.merge!({
      "image_url" => self.image_url,
      "image_thumb_url" => self.image_url(:thumb),
      "edit_pic_path" => (self.new_record? ? nil : Rails.application.routes.url_helpers.edit_pic_path(self)),
      "show_pic_path" => (self.new_record? ? nil : Rails.application.routes.url_helpers.pic_path(self))
    })
    hash
  end

  def get_lat
    self.latitude ? self.latitude.round(3) : "undefined"
  end

  def get_lon
    self.longitude ? self.longitude.round(3) : "undefined"
  end

  def get_desc
    (self.description.empty? or self.description.nil?) ? "No description." : self.description
  end

  def next_pic
    self.class.where("id > ?", id).order("id desc").first
  end

  def prev_pic
    self.class.where("id < ?", id).order("id desc").first
  end

  # def print_metadata
  #   md = ""
  #   hash = YAML::load self.metadata
  #   hash.each do |k,v|
  #     md += "#{k}: #{v.to_s}, "
  #   end
  #   md.slice(0..-3) # remove last ", "
  # end

  def destroy_image
    self.remove_image!
  end

  def parse_exif
    exif = EXIFR::JPEG.new(image.path)
    self.taken_at = exif.date_time

    self.metadata = {
      width: exif.width,
      height: exif.height,
      model: exif.model,
      exposure_time: exif.exposure_time.to_s,
      f_number: exif.f_number.to_f
    }
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  attr_accessible :email, :password, :password_confirmation

  validates_uniqueness_of :email
  validates_presence_of :password, :on => :create

  MAX_USERS = 1

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery

  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

end

app/controllers/pics_controller.rb
class PicsController < ApplicationController

  before_filter :authorize, :except => [:index, :map, :show]

  # GET /pics
  # GET /pics.json
  def index
    @pics = Pic.order("created_at DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pics }
      format.atom { render layout: false }
    end
  end

  # GET /pics/map
  def map
    @pics = Pic.all
    @selected_pic_id = params[:pic_id]
  end

  # GET /pics/1
  # GET /pics/1.json
  def show
    @pic = Pic.find(params[:id])
    @pics = Pic.all

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pic }
    end
  end

  # GET /pics/new
  # GET /pics/new.json
  def new
    @pic = Pic.new
    @pic.longitude = params[:lon] if params[:lon]
    @pic.latitude  = params[:lat] if params[:lat]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pic }
    end
  end

  # GET /pics/1/edit
  def edit
    @pic = Pic.find(params[:id])
  end

  # POST /pics
  # POST /pics.json
  def create
    @pic = Pic.new(params[:pic])

    respond_to do |format|
      if @pic.save
        format.html { redirect_to pics_url, notice: 'Pic was successfully created.' }
        format.json { render json: @pic, status: :created, location: @pic }
      else
        format.html { render action: "new" }
        format.json { render json: @pic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pics/1
  # PUT /pics/1.json
  def update
    @pic = Pic.find(params[:id])

    respond_to do |format|
      if @pic.update_attributes(params[:pic])
        format.html { redirect_to pics_url, notice: 'Pic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pics/1
  # DELETE /pics/1.json
  def destroy
    @pic = Pic.find(params[:id])
    @pic.destroy

    respond_to do |format|
      format.html { redirect_to pics_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  # GET /sessions/new
  def new
    redirect_to(root_url, :notice => "already logged in.") if current_user
  end

  # POST /sessions
  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid."
      render "new"
    end
  end

  # DELETE /sessions/:id
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    redirect_to(root_url, :notice => "No more users allowed.") if User.all.size >= User::MAX_USERS
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.haml
!!!
%html
  %head
    %title Openpicsmap
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application", "http://www.openlayers.org/api/OpenLayers.js"
    = javascript_tag "window.logged_in = #{current_user ? 1 : 0};" # just for map functions
    = auto_discovery_link_tag :atom, "/pics.atom"
    = csrf_meta_tags
  %body
    #nav= render "shared/nav"
    #content= yield
    #footer= render "shared/footer"

app/views/pics/_form.haml
= form_for(@pic, :html => { :multipart => true }) do |f|

  - if @pic.errors.any?
    #error_explanation
      %h2
        = pluralize(@pic.errors.count, "error")
        prohibited this pic from being saved:
      %ul
        - @pic.errors.full_messages.each do |msg|
          %li= msg

  %br
  .field
    - if @pic.new_record?
      = f.label :image
      %br
      = f.file_field :image
    - else
      = image_tag @pic.image.url(:medium)

  .field
    = f.label :title
    %br
    = f.text_field :title

  .field
    = f.label :description
    %br
    = f.text_area :description, :rows => 4

  - if not @pic.new_record?
    .field
      = f.label :taken_at
      %br
      = f.date_select :taken_at

  / .field
  /   = f.label :address
  /   %br/
  /   = f.text_field :address

  %br
  %div#form_map{data: { point: @pic.to_json }}

  %br
  .field
    = f.label :latitude
    %br
    = f.text_field :latitude, :class => 'js-pic-latitude', :size => 12, :readonly => :readonly
  .field
    = f.label :longitude
    %br
    = f.text_field :longitude, :class => 'js-pic-longitude', :size => 12, :readonly => :readonly

  .actions
    = f.submit

:javascript
  $(document).ready(function() {
    OPM.Map.init_form("form_map");
  });

app/views/pics/edit.haml
.form_container

  %h1 Editing pic
  = render 'form'

app/views/pics/index.haml
#grid
  - @pics.each do |pic|
    .cell
      .pic{:id => "pic_#{pic.id}"}
        = link_to pic do
          = image_tag pic.image_url(:medium).to_s if pic.image # pic.image.url(:medium)
        .caption
          %h4= pic.title
          .line
            - if pic.taken_at
              = "taken at #{pic.taken_at}"
              ·
            = link_to "Map", map_pics_path(:pic_id => pic.id)
            - if current_user
              ·
              = link_to "Edit", edit_pic_path(pic), :class => "edit"
              ·
              = link_to "Delete", pic, :method => :delete, :data => { :confirm => "Are you sure?" }, :class => "delete"

app/views/pics/map.haml
%div#map{data: { points: @pics.to_json, selected_id: @selected_pic_id }}

:javascript
  $(document).ready(function() {
    OPM.Map.init("map", true);
  });

app/views/pics/new.haml
.form_container

  %h1 New pic
  = render 'form'

app/views/pics/show.haml
#show-pic

  #pic-header
    .pic-info
      %h1
        = @pic.title
        - if current_user
          = link_to "edit", edit_pic_path(@pic), :class => "edit"
      %ul.details
        %li
          = @pic.get_desc
        %li.dates
          - if @pic.taken_at
            Taken at
            = @pic.taken_at.strftime("%d %B %Y");
            ·
          Uploaded
          = distance_of_time_in_words @pic.created_at, Time.now.utc
          ago

    #show-map{data: { points: @pics.to_json, selected_id: @pic.id }}

  .nav-pic
    .next= link_to "next >", @pic.next_pic if @pic.next_pic
    .prev= link_to "< previous", @pic.prev_pic if @pic.prev_pic

  .img-wrap
    = link_to @pic.image.url do
      = image_tag @pic.image.url, :class => "full_width"

  / .metadata
  /   Metadata:
  /   = @pic.print_metadata(true)

:javascript
  $(document).ready(function() {
    OPM.Map.init("show-map", false);
  });

app/views/shared/_footer.haml
This platform is GPL licenced and available on
= link_to "GitHub", "https://github.com/mllocs/openpicsmap", :target => "blank"
·
The owner reserves all rights of the pictures
© 2012

app/views/shared/_nav.haml
.left
  %h1= link_to "OpenPicsMap", root_path

.right
  = link_to "Gallery", pics_path
  = link_to "Map", map_pics_path
  = link_to "New pic", new_pic_path if current_user
  - if current_user
    = link_to "Logout", logout_path
  / - else
  /   = link_to "Login", login_path

app/views/users/new.haml
.form_container

  %h1 Sign Up
  = form_for @user do |f|
    - if @user.errors.any?
      .error_messages
        %h2 Form is invalid
        %ul
          - @user.errors.full_messages.each do |message|
            %li= message

    .field
      = f.label :email
      %br/
      = f.text_field :email
    .field
      = f.label :password
      %br/
      = f.password_field :password
    .field
      = f.label :password_confirmation
      %br/
      = f.password_field :password_confirmation
    .actions= f.submit "Sign Up"